-- Tabla principal para Horario y Tareas
CREATE TABLE schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_number INTEGER NOT NULL,
    cell_key TEXT NOT NULL, -- Ej: "0-0" para materia, "mil-1" para militar
    task TEXT,
    due_date DATE,
    instructor TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(week_number, cell_key)
);

-- Habilitar Realtime para esta tabla
ALTER PUBLICATION supabase_realtime ADD TABLE schedules;

-- (Opcional) Tabla de Auditoría simplificada
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cell_key TEXT,
    action TEXT,
    old_data JSONB,
    new_data JSONB,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
