-- ============================================================
-- Tabla principal para Horario y Tareas
-- ============================================================
CREATE TABLE IF NOT EXISTS schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_number INTEGER NOT NULL,
    cell_key TEXT NOT NULL, -- Ej: "0-0" para materia, "mil-1" para militar
    task TEXT,
    due_date DATE,
    instructor TEXT,
    type TEXT DEFAULT 'tarea',
    notes TEXT,
    status TEXT DEFAULT 'pendiente',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(week_number, cell_key)
);

-- Si la tabla ya existía sin estas columnas (la app las necesita
-- para guardar tipo, notas y estado de cada tarea), agrégalas así:
ALTER TABLE schedules ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'tarea';
ALTER TABLE schedules ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE schedules ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pendiente';

-- Habilitar Realtime para esta tabla
ALTER PUBLICATION supabase_realtime ADD TABLE schedules;

-- ============================================================
-- Seguridad a nivel de fila (RLS)
-- La app usa la "publishable/anon key" desde el navegador, así que
-- la tabla necesita politicas que permitan leer y escribir con esa
-- clave. Sin estas politicas, todas las operaciones fallan.
-- ============================================================
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir lectura publica" ON schedules;
CREATE POLICY "Permitir lectura publica"
  ON schedules FOR SELECT
  TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS "Permitir escritura publica" ON schedules;
CREATE POLICY "Permitir escritura publica"
  ON schedules FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir actualizacion publica" ON schedules;
CREATE POLICY "Permitir actualizacion publica"
  ON schedules FOR UPDATE
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir borrado publico" ON schedules;
CREATE POLICY "Permitir borrado publico"
  ON schedules FOR DELETE
  TO anon, authenticated
  USING (true);

-- ============================================================
-- (Opcional) Tabla de Auditoria simplificada
-- ============================================================
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cell_key TEXT,
    action TEXT,
    old_data JSONB,
    new_data JSONB,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
